wip start on trying to transform React.RefAttributes -- need program at transform time -- currently crashing at checker.getSymbolAtLocation
With, embarrassingly for TS, a runtime type error.  Inside the type-checker.

    TypeError: Cannot read properties of undefined (reading 'exports')

      279 |       if (ts.isTypeReferenceNode(node) && ts.isQualifiedName(node.typeName)) {
      280 |         console.log(node.typeName);
    > 281 |         const symbol = checker.getSymbolAtLocation(node.typeName);
          |                                ^
      282 |         // const decl = symbol.declarations[0];
      283 |         // console.log(checker.getTypeAtLocation(node.typeName));
      284 |         // return node;

      at resolveNameHelper (node_modules/typescript/lib/typescript.js:47466:70)
      at resolveName (node_modules/typescript/lib/typescript.js:47393:20)
      at resolveEntityName (node_modules/typescript/lib/typescript.js:48688:42)
      at resolveEntityName (node_modules/typescript/lib/typescript.js:48696:33)
      at getSymbolOfNameOrPropertyAccessExpression (node_modules/typescript/lib/typescript.js:82275:24)
      at getSymbolAtLocation (node_modules/typescript/lib/typescript.js:82359:28)
      at Object.getSymbolAtLocation (node_modules/typescript/lib/typescript.js:46199:31)
      at visitor (src/parse/transformers.ts:281:32)

The argument I'm passing there is indeed a genuine ts.Node, which is
the type that function is supposed to take.  So TS really has no excuse.